version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@1.8

defaults: &defaults
  working_directory: ~/a
  docker:
    - image: vuejs/ci

jobs:
  install:
    <<: *defaults
    parameters:
      package_name:
        type: string
    steps:
      - checkout:
          path: ~/b
      - run: ls
      - run: mkdir install
      - run: touch install/README.md
      - run: ls install
      - run: pwd
      - persist_to_workspace:
          root: ~/
          paths:
            - b
  build:
    <<: *defaults
    parameters:
      package_name:
        type: string
    steps:
      - attach_workspace:
          at: ~/
      - run: ls
      - run: mkdir build
      - run: touch build/README.md
      - run: ls build
      - run: pwd
      - persist_to_workspace:
          root: ~/
          paths:
            - www
  upload:
    <<: *defaults
    parameters:
      package_name:
        type: string
    working_directory: ~/www
    steps:
      - attach_workspace:
          at: ~/
      - run: ls
      - run: pwd
      - run: mkdir bucket
      - run: pwd
      - run: cp -a/. bucket/
      - run: cd bucket
      - run: pwd
      - run: ls
      

workflows:
  version: 2
  support_install_build_upload:
    jobs:
      - install:
          name: support:install
          package_name: support-revas-app
      - build:
          name: support:build
          package_name: support-revas-app
          requires:
            - support:install
      - upload:
          name: support:upload
          package_name: support-revas-app
          requires:
            - support:build
